build if not exists

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,11 +9,19 @@ notifications:
     on_failure: change
 
 install:
-  - export NODE_VERSION=$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
-  - echo $NODE_VERSION
+  - |
+    export REPO=$TRAVIS_REPO_SLUG
+    export BRANCH=master
+    export NODE_VERSION=$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
+
+#install:
+#  - export NODE_VERSION=$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-v(.*)\.pkg</a>.*|\1|p')
+#  - echo $NODE_VERSION
+#  - export IMAGE=$TRAVIS_REPO_SLUG:$NODE_VERSION
+#  - echo $IMAGE
 #  - sudo curl -sSL https://get.docker.com/ | sh
-  - docker version
-  - docker info
+#  - docker version
+#  - docker info
 #  - sudo rm /usr/local/bin/docker-compose
 #  - export DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)
 #  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
@@ -23,12 +31,17 @@ install:
 #  - docker-compose version
 
 script:
-  - export IMAGE=$TRAVIS_REPO_SLUG:$NODE_VERSION
+  - docker version
+  - docker info
   - docker pull $IMAGE || echo 'image not found'
   - |
-    if [[ "$(docker images -q $IMAGE 2> /dev/null)" == "" ]]; then
-      docker build -t $IMAGE -t $TRAVIS_REPO_SLUG:latest --build-arg NODE_VERSION=$NODE_VERSION .
-      docker images
-      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
-      docker push $TRAVIS_REPO_SLUG
+    echo "Current version: $REPO:$NODE_VERSION"
+    docker pull $REPO:$NODE_VERSION || echo 'image not found'
+    if [[ "$(docker images -q $REPO:$NODE_VERSION 2> /dev/null)" == "" ]]; then
+      curl -X POST --header "Content-Type: application/json" -d "{}" https://circleci.com/api/v1.1/project/gh/$REPO/tree/$BRANCH?circle-token=907565f9d37e10a88dda4901e72ba88d372d1618
+      docker build -t $REPO:$NODE_VERSION --build-arg NODE_VERSION=$NODE_VERSION .
     fi
+    docker tag $REPO:$NODE_VERSION $REPO:latest
+    docker images
+    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
+    docker push $REPO
